import { InvalidRequestParamError } from '@/application/error/invalid-request-param-error';

import { parseJobIdParam } from '../job-id-param.validator';

describe('parseJobIdParam', () => {
  it('should accept a UUID generated by Postgres gen_random_uuid()', () => {
    expect(parseJobIdParam('6f1c2a9e-4b7d-4c1a-9f3e-2d8b5a7c9e10')).toBe('6f1c2a9e-4b7d-4c1a-9f3e-2d8b5a7c9e10');
  });

  it.each(['42', '-1', 'abc', '', '6f1c2a9e-4b7d-4c1a-9f3e', '6f1c2a9e4b7d4c1a9f3e2d8b5a7c9e10', undefined, 42])(
    'should throw InvalidRequestParamError (400) for %p',
    value => {
      expect(() => parseJobIdParam(value)).toThrow(InvalidRequestParamError);

      try {
        parseJobIdParam(value);
      } catch (error) {
        expect((error as InvalidRequestParamError).status).toBe(400);
        expect((error as InvalidRequestParamError).data).toEqual({ jobId: value });
      }
    }
  );
});
