apiVersion: v1
kind: Secret
metadata:
  name: 4frames-aws-secret
  namespace: default
  labels:
    app: 4frames-api
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
  AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'
