apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: localstack-aws
  namespace: default
  labels:
    app: 4frames-worker
spec:
  secretTargetRef:
    - parameter: awsAccessKeyID
      name: 4frames-aws-secret
      key: AWS_ACCESS_KEY_ID
    - parameter: awsSecretAccessKey
      name: 4frames-aws-secret
      key: AWS_SECRET_ACCESS_KEY
