apiVersion: v1
kind: Secret
metadata:
  name: 4frames-db-secret
  namespace: default
  labels:
    app: 4frames-api
type: Opaque
stringData:
  DB_USERNAME: '${DB_USERNAME}'
  DB_PASSWORD: '${DB_PASSWORD}'
  DB_HOST: '${DB_HOST}'
  DB_PORT: '${DB_PORT}'
  DB_DATABASE: '${DB_DATABASE}'
  DB_SCHEMA: '${DB_SCHEMA}'
  JWT_SECRET_KEY: '${JWT_SECRET_KEY}'
