apiVersion: v1
kind: Service
metadata:
  name: worker
  namespace: 4frames
  labels:
    app.kubernetes.io/name: worker
    app.kubernetes.io/part-of: 4frames
spec:
  selector:
    app.kubernetes.io/name: worker
  ports:
    - name: health
      port: 9100
      targetPort: health
