export enum DomainErrorTypes {
  INVALID_ARGUMENT = 'INVALID_ARGUMENT',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  INVALID_STATE = 'INVALID_STATE',
  PRECONDITION_FAILED = 'PRECONDITION_FAILED',
  VALIDATION_ERROR = 'VALIDATION_ERROR'
}
